### ISSUE TITLE
Should we have Triangles where 4 dual carriageways meet?

### ISSUE THREAD

**Issue by Athelena** [liberostelios/roads_generator#13]
![image](https://user-images.githubusercontent.com/19203377/87688251-09f84780-c787-11ea-83b0-e704dd297b95.png)

**Comment by liberostelios** [comment]
<img width="399" alt="Screenshot 2020-10-02 at 23 15 35" src="https://user-images.githubusercontent.com/1896327/94970552-32c9e680-0505-11eb-80b0-6a8cb714165c.png">
 Fixed as such.
